#Lecture 1

In [3]:
# This is an example of a vector in python.

import numpy as np

asList = [1,2,3]
asArray = np.array([1,2,3]) # 1D array
rowVec = np.array([ [1,2,3] ]) # row
colVec = np.array([ [1],[2],[3] ]) # column

print(f'asList: {np.shape(asList)}')
print(asList)


print(f'asArray: {asArray.shape}')
print(asArray)

print(f'rowVec: {rowVec.shape}')
print(rowVec)

print(f'colVec: {colVec.shape}')
print(colVec)


asList: (3,)
[1, 2, 3]
asArray: (3,)
[1 2 3]
rowVec: (1, 3)
[[1 2 3]]
colVec: (3, 1)
[[1]
 [2]
 [3]]


In [6]:
# Scalar * Vector
s = 2
a = [3,4,5] # as list
b = np.array(a) # as np array
print(a*s)
print(b*s)

[3, 4, 5, 3, 4, 5]
[ 6  8 10]


In [ ]:
# Scalar + Vector
s = 2
v = np.array([3,6])
s+v

In [8]:
#Transpose
rowVec = np.array([ [1,2,3] ]) # row
colVec = rowVec.transpose()


print(f'rowVec: {rowVec.shape}')
print(rowVec)

print(f'colVec: {colVec.shape}')
print(colVec)

rowVec: (1, 3)
[[1 2 3]]
colVec: (3, 1)
[[1]
 [2]
 [3]]


In [11]:
# Magnitude
v = np.array([1,2,3,7,8,9])
v_dim = len(v)  # math dimensionality
v_mag = np.linalg.norm(v) # math magnitude, length, or norm

print("len()")
print(v_dim)

print("np.linalg.norm()")
print(v_mag)


len()
6
np.linalg.norm()
14.422205101855956


In [5]:
# Dot Product
v = np.array([1,2,3,4])
w = np.array([5,6,7,8])
np.dot(v,w)

70

In [6]:
#Dot Product and angle
v = np.array([1,0])
w = np.array([1,1])
dot = np.dot(v,w)
angle = np.arccos(dot/(np.linalg.norm(v)*np.linalg.norm(w)))
angle = np.degrees(angle)
print(f"The dot product is {dot}. The angle is {angle:.2f} degrees",sep="\n")

The dot product is 1. The angle is 45.00 degrees


In [14]:
# Distributive
a = np.array([ 0,1,2 ])
b = np.array([ 3,5,8 ])
c = np.array([ 13,21,34 ])

# the dot product is distributive
res1 = np.dot( a, b+c )
print(res1)
res2 = np.dot( a,b ) + np.dot( a,c )
print(res2)


110
110


In [10]:
# Correlation
def pearson_correlation(x, y):
 """
 Compute Pearson correlation coefficient between two vectors.
 """
 # Ensure numpy arrays
 x = np.array(x)
 y = np.array(y)
 # Mean-centering the vectors
 x = x - np.mean(x)
 y = y - np.mean(y)
 # Compute Pearson correlation coefficient
 correlation = np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))
 return correlation

In [7]:
# Correlation
import plotly.express as px
math = np.array([87, 65, 94, 45, 76])
physics = np.array([99, 84, 82, 58, 79])
# Convert the numpy arrays to lists for Plotly Express compatibility
math_scores = list(math)
physics_scores = list(physics)
# Create a scatter plot
fig = px.scatter(x=math_scores, y=physics_scores, labels={'x': 'Math Scores', 'y': 'Physics Scores'},title='Scatter Plot of Math vs Physics Scores')
# Show the plot
fig.show()

In [11]:
# Example vectors
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4, 5, 6])
# Calculate and print the Pearson correlation coefficient
print(pearson_correlation(math, physics))
print(np.corrcoef(math, physics))

0.781436194238763
[[1.         0.78143619]
 [0.78143619 1.        ]]
